### ISSUE TITLE
实现水平垂直居中

### ISSUE THREAD

**Issue by vivipure** [vivipure/bagu-of-fe#209]
# 答案

## 1. flex实现
```CSS
.father {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

## 2. 绝对定位配合 transform
```CSS
.father {
    position: relative;
}
.son {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```

## 3. 绝对定位配合 margin: auto;
```CSS
.father {
    position: relative;
}
.son {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
    margin: auto;
}
```
