### ISSUE TITLE
300ms 延时解决的办法

### ISSUE THREAD

**Issue by vivipure** [vivipure/bagu-of-fe#253]
# 答案
1. fastclick 解决
2. viewport 设置
```html
<meta name="viewport" content="width=device-width">
```
3. css 处理
```css
html {
  touch-action: manipulation;
}
```
